@startuml 国际政治学

历史 -> 大航海时代: 15世纪末至17世纪，核心命题：海洋的崛起，国际秩序开启
历史 -> 大航海时代: 代表国家：\n从古典的观念当中脱胎出近代的国家观念，代表国家就是法国；\n从古老的陆地视角当中又分化出海洋视角，代表国家是英国。
历史 -> 大航海时代: 国际秩序就是以全球为单位，以国家为基本行为体，以贸易\n和战争为基本的互动方式，以国际法和国际条约为基本的行为\n规范，从而形成的一种秩序。在这种国际秩序下，国家之间一律平等。
历史 -> 大航海时代: 西班牙人奠定了国际法的雏形
历史 -> 大航海时代: 法国反哈布斯堡帝国，“国家理由”出现。使得尊奉这个观念\n的国家，思考一切问题都开始只从本国的利益出发，绝不会再\n从一个超越本国之上、普世帝国秩序的角度出发。
历史 -> 大航海时代: 大航海时代，作为落后者的英国被迫做出观念上的转型，打\n败了西班牙的无敌舰队，成为了海洋霸主。
历史 -> 大航海时代: 1648年的威斯特伐利亚体系，形成人类的第一个国际体系


大航海时代 -> 大革命时代: 核心命题：英国的工业革命、法国的政治革命
大航海时代 -> 大革命时代: 英国的工业革命和法国的政治革命的全新玩法，可以\n用一个词来表达，就是理性化。
大航海时代 -> 大革命时代: 进入大众政治时代，需要治理的内容急剧增多，必须\n提升治理效率，把治理办法给抽象化、规则化，用同一套规则来\n应对各种层出不穷的问题，这就是所谓的理性化。
大航海时代 -> 大革命时代: 在英国工业革命的套路下，理性化主要是在工厂的管\n理结构这个层面上展开。而在政治革命的套路下，法国的理性化\n主要是在政府的官僚制这个层面上展开。
大航海时代 -> 大革命时代: 英国推动自动贸易，其实是主导了全世界通行的普遍\n贸易规则，这也是英国成为霸主国的关键所在



大革命时代 -> 大战争时代: 背景：技术演化速度远快于国际秩序演化速度，外交\n斡旋机制作废，战争武器空前发展
大革命时代 -> 大战争时代: 核心命题：民族主义 VS 普世主义


大战争时代 -> 大阵营时代: 核心命题：关于人类命运前途的争论


大阵营时代 -> 大颠覆时代: 核心命题：关于对未来的想象

大颠覆时代 -> 未来
@enduml
